services:
  bot:
    image: dimachizh123/secret-santa
    container_name: secret-santa
    env_file:
      - app/config.env
    volumes:
      - ./data/secret_santa.db:/bot/secret_santa.db
    restart: unless-stopped