services:
  bot:
    image: d1mchik/secret-santa-bot
    container_name: secret-santa
    env_file:
      - app/config.env
    volumes:
      - ./data/secret_santa.db:/bot/secret_santa.db
    restart: unless-stopped